"""user tokens

Revision ID: 264ebadb3953
Revises: e913c6d494b7
Create Date: 2025-02-17 10:38:09.875322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264ebadb3953'
down_revision = 'e913c6d494b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_expiration', sa.DateTime(), nullable=True))
        batch_op.drop_column('token_exporation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_exporation', sa.DATETIME(), nullable=True))
        batch_op.drop_column('token_expiration')

    # ### end Alembic commands ###
