"""add followers table

Revision ID: 950b51fa669f
Revises: 9db65f6bbbdc
Create Date: 2025-02-14 11:41:28.635453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950b51fa669f'
down_revision = '9db65f6bbbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
